import type { Session } from './types';

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    name: 'Ethiopia Yirgacheffe Tasting',
    date: '2024-07-20',
    evaluations: [
      {
        id: 'eval-1a',
        coffeeName: 'Ethiopia Yirgacheffe Washed',
        roastLevel: 'light',
        dryFragrance: 'high',
        wetAroma: 'high',
        acidityIntensity: 'high',
        bodyIntensity: 'low',
        scores: [
          { name: 'Aroma', value: 8.75 },
          { name: 'Flavor', value: 8.5 },
          { name: 'Aftertaste', value: 8.25 },
          { name: 'Acidity', value: 8.75 },
          { name: 'Body', value: 8.0 },
          { name: 'Balance', value: 8.5 },
          { name: 'Uniformity', value: 10 },
          { name: 'Clean Cup', value: 10 },
          { name: 'Sweetness', value: 10 },
        ],
        uniformity: 10,
        cleanCup: 10,
        sweetness: 10,
        overallScore: 88.5,
      },
      {
        id: 'eval-1b',
        coffeeName: 'Ethiopia Yirgacheffe Natural',
        roastLevel: 'light',
        dryFragrance: 'high',
        wetAroma: 'high',
        acidityIntensity: 'medium',
        bodyIntensity: 'medium',
        scores: [
          { name: 'Aroma', value: 8.5 },
          { name: 'Flavor', value: 8.75 },
          { name: 'Aftertaste', value: 8.5 },
          { name: 'Acidity', value: 8.25 },
          { name: 'Body', value: 8.5 },
          { name: 'Balance', value: 8.75 },
          { name: 'Uniformity', value: 10 },
          { name: 'Clean Cup', value: 10 },
          { name: 'Sweetness', value: 10 },
        ],
        uniformity: 10,
        cleanCup: 10,
        sweetness: 10,
        overallScore: 89.25,
      },
    ],
  },
  {
    id: 'session-2',
    name: 'Colombia Supremo Analysis',
    date: '2024-07-18',
    evaluations: [
      {
        id: 'eval-2a',
        coffeeName: 'Colombia Supremo, Finca La Esmeralda',
        roastLevel: 'medium',
        dryFragrance: 'medium',
        wetAroma: 'medium',
        acidityIntensity: 'medium',
        bodyIntensity: 'high',
        scores: [
          { name: 'Aroma', value: 8.25 },
          { name: 'Flavor', value: 8.5 },
          { name: 'Aftertaste', value: 8.0 },
          { name: 'Acidity', value: 8.25 },
          { name: 'Body', value: 8.5 },
          { name: 'Balance', value: 8.75 },
          { name: 'Uniformity', value: 10 },
          { name: 'Clean Cup', value: 10 },
          { name: 'Sweetness', value: 10 },
        ],
        uniformity: 10,
        cleanCup: 10,
        sweetness: 10,
        overallScore: 86.75,
      },
    ],
  },
  {
    id: 'session-3',
    name: 'Sumatra Mandheling Review',
    date: '2024-07-15',
    evaluations: [
      {
        id: 'eval-3a',
        coffeeName: 'Sumatra Mandheling Grade 1',
        roastLevel: 'dark',
        dryFragrance: 'medium',
        wetAroma: 'low',
        acidityIntensity: 'low',
        bodyIntensity: 'high',
        scores: [
          { name: 'Aroma', value: 8.0 },
          { name: 'Flavor', value: 8.25 },
          { name: 'Aftertaste', value: 8.5 },
          { name: 'Acidity', value: 7.5 },
          { name: 'Body', value: 9.0 },
          { name: 'Balance', value: 8.0 },
          { name: 'Uniformity', value: 10 },
          { name: 'Clean Cup', value: 10 },
          { name: 'Sweetness', value: 10 },
        ],
        uniformity: 10,
        cleanCup: 10,
        sweetness: 10,
        overallScore: 85.5,
      },
    ],
  },
];
